name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install -d

      - name: Run linting
        run: |
          make lint

      - name: Check for any unknown changes
        run: |
          git diff --exit-code


  unit-tests:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install -d

      - name: Run tests
        run: |
          make unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v2

      - name: Setup git vars
        id: vars
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=commit;]$(git rev-parse --short "$GITHUB_SHA")"

      - name: Create .env file
        run: |
          touch .env
          echo ENV=${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.commit }} >> .env

      - name: Set up Python 3.8.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Setup up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install -d

      - name: Configure awscli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy pretzel
        run: |
          make deploy

      - name: Integration tests
        run: |
          make integration

      - name: Destroy pretzel
        if: always()
        run: |
          make destroy

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Setup git vars
        id: vars
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create .env file
        run: |
          touch .env
          echo ENV=${{ steps.vars.outputs.branch }} >> .env

      - name: Set up Python 3.8.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Setup up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install -d

      - name: Configure awscli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy pretzel
        run: |
          make deploy
